" Plugins will be downloaded under the specified directory.
call plug#begin('~/.vim/plugged')

" Declare the list of plugins.
Plug 'tpope/vim-surround'
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'

" List ends here. Plugins become visible to Vim after this call.
call plug#end()

" Make CtrlP use ag for listing the files. Way faster and no useless files.
if executable('ag')
  let g:ctrlp_user_command = 'ag %s -l --hidden --nocolor -g ""'
  let g:ctrlp_use_caching = 0
endif

" If we have a sintax checker for the given file extension, use it
filetype plugin indent on

set runtimepath^=~/.vim/bundle/ctrlp.vim

" allow backspacing over everything in insert mode
set backspace=indent,eol,start

" Numbers
set number
set numberwidth=5

if &t_Co >= 256 || has('gui_running') 
  if filereadable(expand('$HOME/.vim/colors/mustang.vim'))
    colorscheme mustang
  endif
endif

if &t_Co > 2 || has('gui_running')
  " switch syntax highlighting on, when the terminal has colors
  syntax on
endif

" Identation
set tabstop=2    " Use 2 spaces
set shiftwidth=2 " Use 2 spaces when indent with shift
set expandtab   

" Open new split panes to right and bottom, which feels more natural
set splitbelow
set splitright
